### ISSUE TITLE
Installing pyzip with pip > 23.1 fails

### ISSUE THREAD

**Issue by constantin-huetterer** [ipazc/pyzip#2]
When installing pyzip with a pip version newer than 23.1, the following error occurs:
<details>
<summary>Error message</summary>

```bash
pip install pyzip
Collecting pyzip
  Using cached pyzip-0.2.0.tar.gz (6.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/constantin.huetterer/.pyenv/versions/3.11.8/envs/test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/constantin.huetterer/.pyenv/versions/3.11.8/envs/test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/constantin.huetterer/.pyenv/versions/3.11.8/envs/test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zv/jttqyxls773b0svh4b03lyw9zf7b_z/T/pip-build-env-ni643c30/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zv/jttqyxls773b0svh4b03lyw9zf7b_z/T/pip-build-env-ni643c30/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/zv/jttqyxls773b0svh4b03lyw9zf7b_z/T/pip-build-env-ni643c30/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/zv/jttqyxls773b0svh4b03lyw9zf7b_z/T/pip-build-env-ni643c30/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
      ImportError: cannot import name 'setuptools' from 'setuptools' (/private/var/folders/zv/jttqyxls773b0svh4b03lyw9zf7b_z/T/pip-build-env-ni643c30/overlay/lib/python3.11/site-packages/setuptools/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
</details>

As a workaround, you can downgrade pip: `pip install pip==23.0 `. 

There is also a PR addressing this issue (#1).

**Comment by piglubhai4-sys** [comment]
termux-setup-storage
